customhost = "database-1.cfo6hq5bnwmq.us-east-1.rds.amazonaws.com"
customuser = "root"
custompass = "password"
customdb = "studentdb_rds"
custombucket = "202011012bucket"
customregion = "us-east-1"
